// <auto-generated />
using DesafioPaggCerto.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioPaggCerto.Migrations
{
    [DbContext(typeof(DesafioContext))]
    [Migration("20181109031614_AddTableAcquirer")]
    partial class AddTableAcquirer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioPaggCerto.Models.EntityModel.Acquirer.Acquirer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("Nome")
                        .HasMaxLength(255);

                    b.Property<decimal>("Tax")
                        .HasColumnName("Taxa")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.ToTable("Adquirente","pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
